# Python Basics

This is a Jupyter notebook that takes you through many basic commands and concepts in Python. It is a companion to the MATLAB basics live script.
To execute through this notebook, use up and down arrows to move between sections (highlight in a blue box when you are in them) and then press CTLR-Enter. Output (if there is any) shows up on under each executed cell.

## Loading packages

One of the big immediate differences of python (compared to MATLAB) is that while there are many built in functions in the basic Python environment, for much of the functionality that you might use, you must install and load in packages. Anaconda, which you can download and setup fairly easily has many "standard" packages already in its environment. Once you start to do fancier or more non-standard things, you may need to install new packages, which is generally straightforward to do using the "conda install" command on the command line (this can also be done though the Anaconda GUI). For scientific computing and basic plotting, the most useful packages are numpy, matplotlib and scipy. These are all part of the standard anaconda environment.

In [42]:
import numpy as np
import matplotlib.pyplot as plt
import scipy

## Executing Commands

In normal python code (not a notebook like this) output is automatically supressed. In a notebook all output except the last line of a cell is suppressed. Otherwise, basic arithmetic syntax is the same as MATLAB, except for exponents.

In [43]:
3*5

15

In [44]:
3*5
8**2

64

## Assign variables and data types

Python is more strict about data types (particularly numbers) than MATLAB. In MATLAB integers and doubles will often be automatically converted by a function depending on what is needed. In Python, many functions require inputs to be one or the other and will give errors if you are not careful with input type

In [45]:
a1=3
a1

3

In [46]:
a2=3.0
a2

3.0

In [47]:
a3 = 'hello'
a3

'hello'

In [48]:
a4 = True #be careful to capitalize logical types in Python
a4

True

In [49]:
a5 = [1,5,9]
a5

[1, 5, 9]

To do column vector and fancier array algebra, you need to define a numpy array which has more capabilities than the basic Python row vector

In [51]:
a6 = np.array([[2, 4, 8]]).T
a6

array([[2],
       [4],
       [8]])

In [52]:
a7 = np.array([[1, 8], [4, 9]])
a7

array([[1, 8],
       [4, 9]])

## Creating useful vectors/matrices

arange is the Python equivalent of the colon in MATLAB. BUT: Python indexing is not inclusive of the ending index (more on indexing in the next section)

In [53]:
b1 = np.arange(2,8)
b1

array([2, 3, 4, 5, 6, 7])

In [54]:
b2 = np.arange(2,8,0.5)
b2

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5])

In [55]:
b3 = np.linspace(0.4,8.2,10)
b3

array([0.4       , 1.26666667, 2.13333333, 3.        , 3.86666667,
       4.73333333, 5.6       , 6.46666667, 7.33333333, 8.2       ])

In [56]:
b4 = np.zeros([10,11])
b4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [57]:
b5 = np.ones([10,11])
b5

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

numpy has some functions that are not imported by default, like those contained in matlib, these need to be imported separately

In [58]:
import numpy.matlib
b6 = np.matlib.repmat(b1, 2, 2)
b6

array([[2, 3, 4, 5, 6, 7, 2, 3, 4, 5, 6, 7],
       [2, 3, 4, 5, 6, 7, 2, 3, 4, 5, 6, 7]])

In [59]:
[b7,b8] = np.meshgrid(b2, b3, sparse=False, indexing='ij') #need to specify type of indexing in Python's meshgrid, ij is most common, and the same as matlab
b7

array([[2. , 2. , 2. , 2. , 2. , 2. , 2. , 2. , 2. , 2. ],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ],
       [3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5],
       [4. , 4. , 4. , 4. , 4. , 4. , 4. , 4. , 4. , 4. ],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [5. , 5. , 5. , 5. , 5. , 5. , 5. , 5. , 5. , 5. ],
       [5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5],
       [6. , 6. , 6. , 6. , 6. , 6. , 6. , 6. , 6. , 6. ],
       [6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5],
       [7. , 7. , 7. , 7. , 7. , 7. , 7. , 7. , 7. , 7. ],
       [7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5]])

## Indexing

Indexing is one of the biggest differences between Python and MATLAB. Python is zero-indexed, which means that the first element of vector or array is indexed as '0'. Also, to reference an index in a Python array one uses square brackets '[]', whereas parenthesis '()' are only used to call functions. There are some other key differences which are explored in examples here

In [60]:
c1 = b6[0,0]
c1

2

In [61]:
c1 = b6[1,1]
c1

3

Another key difference is that when using vector indexing (i.e. with colons as you would in MATLAB), the indexing goes from the first index, and then up to BUT NOT INCLUDING the end index. So in the below example [0:2] yields a vector index including index 0 and 1, but not 2. 

In [62]:
c2 = b6[0:2,0]
c2

array([2, 2])

In [63]:
c2 = b6[0,0:6:2] #note that the increment in a python vector index comes at the end (0:6:2 in this example)
c2

array([2, 4, 6])

In [64]:
c3 = b6[0:2,0:2]
c3

array([[2, 3],
       [2, 3]])

In [65]:
c4 = b6[0,-1] #-1 is used instead of "end" to indicate the last element along a dimension of an array
c4

7

In [66]:
c5 = b6[1,b1]
c5

array([4, 5, 6, 7, 2, 3])

## Boolean/Logical Operations

Mostly these work the same as in MATLAB, though booleans are stored as "True" and "False" indexing is a bit different

In [67]:
l1 = b1 < 5
l1

array([ True,  True,  True, False, False, False])

In [68]:
l2 = b1[l1] #logical indexing mostly works the same as in MATLAB, but only works on numpy arrays
l2

array([2, 3, 4])

As we will also see for loops below, conditional statements (if/else) do not have end like in MATLAB, BUT INDENTATION IS IMPORTANT AND ENFORCED IN PYTHON (compared to MATLAB where indentation does not play a role in code execution)

In [69]:
if c1>5 : #use a colon to indicat the end of the logical condition
    print('hurray!')
elif c1<0 : #elif instead of else if
    print('sure...')    
else :
    print('oh no!')

oh no!


In [70]:
l3 = (b1 < 5) & (b1 > 2)
l3

array([False,  True,  True, False, False, False])

In [71]:
l4 = (b1 > 5) | (b1 < 2)
l4

array([False, False, False, False,  True,  True])

## Vector and matrix manipulation and arithmetic

In [74]:
d1 = b6.transpose()
d1

array([[2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6],
       [7, 7],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6],
       [7, 7]])

In [75]:
d2 = np.sum(b6,axis=None)
d2

108

In [76]:
d3 = np.sum(b6,axis=0)
d3

array([ 4,  6,  8, 10, 12, 14,  4,  6,  8, 10, 12, 14])

In [77]:
d4a = np.random.rand(2,12)
d4 = b6*d4a #note the default in Python is elementwise multiplication with *
d4

array([[0.05182577, 2.88377118, 0.83750124, 2.29951658, 4.01020414,
        6.34472926, 1.2274737 , 2.15854208, 1.0339901 , 3.20863496,
        0.87228181, 4.39414637],
       [0.61286673, 0.61685836, 3.97280026, 3.86021309, 1.59030828,
        0.89488079, 0.01793658, 0.11492862, 1.73691939, 3.48309504,
        4.33554735, 5.52299278]])

In [78]:
d5a = np.random.rand(12,2)
d5 = b6 @ d5a #for matrix multiplication use @
d5

array([[26.82811442, 24.36357475],
       [26.82811442, 24.36357475]])

In [79]:
d6a = np.random.rand(3,3)
d6b = np.random.rand(3,1)
x = np.linalg.lstsq(d6a,d6b,rcond=None)
x

(array([[-1.15691255],
        [11.0218247 ],
        [-0.37503269]]),
 array([], dtype=float64),
 3,
 array([1.50369072, 0.78308524, 0.02920718]))

## Loops

In [80]:
e1=0
for i in np.arange(0,10) :   #for loop iterates over the vector i (from 0 to 9) with defined boundaries
    e1 = e1 + (b3[i]**2) 
e1

246.86666666666667

In [81]:
e2 = np.sum(b3**2)
e2

246.86666666666667

In [82]:
e3=0
i=0
while e3 < 10 :   #while loop iterates indeinfitely while a logical operation is still true
    e3=e3 + (b3[i]**2) 
e3

10.080000000000007

## Functions

Lambda functions are used to anonymously define a function inline in Python. Otherwise, they must be defined using def, a colon and indenting

In [83]:
fcn = lambda x: np.exp(np.sin(x)**2) #lambda anonymous function

In [84]:
def fcn2(x):
    return np.exp(np.sin(x)**2)

In [86]:
fcn2(1)

2.0300763806332567